Added README.md file.
toolforge/media-dubiety pull request #1
Opened 2020-03-09 07:40 UTC by Rohan-cod

2020-03-09 16:51 UTC, zhuyifei1999 commented
-1. This completely doesn't explain what the project does, only explains what Toolforge and MediaWiki are. A README should explain about _this_ project, not _some other_ projects. The "website" isn't even the public endpoint, IRC is.

2020-03-09 17:03 UTC, Rohan-cod commented
Actually I wasn't able to find much information about media-dubiety. 
If you can provide me with a link to more information about it I will add important points to the Readme. It would really help me. I will also change the link to point to the correct url.

2020-03-09 17:18 UTC, zhuyifei1999 commented
T129845 is non-public and relates to [these discussions](https://commons.wikimedia.org/w/index.php?sort=relevance&search=%22Influx+of+files+with+embedded+data+%28CSD%23F9%29%22&title=Special:Search&profile=advanced&fulltext=1&advancedSearch-current=%7B%7D&ns4=1), although it has more of the embeddeddata project than this one.

This project is an IRC bot in channels defined in `~tools.media-dubiety/channels.json`. It sends messages such as:
```
<media-dubiety> https://tinyurl.com/CentralAuth/REDACTED (3 edits) uploaded https://commons.wikimedia.org/wiki/File:REDACTED (56.7MiB, 5 min)
<media-dubiety> REDACTED blocks User:REDACTED on simplewiki for: Reciprocal block: Violating the "one-strike" rule
```
The purpose of this project used to be T129845, but right now it's more like "if abuse happens again we would know".

2020-03-09 17:27 UTC, Rohan-cod commented
Thanks for the help @zhuyifei1999, I will update the Readme file with the correct information.
Can you tell me which url I am supposed to add

2020-03-09 17:35 UTC, zhuyifei1999 commented
> Can you tell me which url I am supposed to add.

I'd rather not have a URL; it doesn't have a "webservice" in Toolforge terms and I don't see a reason to document detail abuse-prevention mechanisms publicly.

2020-03-09 17:40 UTC, Rohan-cod commented
I am adding a Readme so that whenever a new user visits the repository he gets some information regarding the project like what it is about, what is the history and other stuff.

2020-03-10 06:52 UTC, Rohan-cod commented
@zhuyifei1999, I have updated the README, please review.

2020-03-10 07:13 UTC, zhuyifei1999 requested changes
Look, I really don't think it's a good idea to advertise anti-abuse mechanisms on the "front page". 

Example messages? Sure. People knows what this does.

Anything about T129845? No thanks. That was for your information only.

2020-03-10 07:13 UTC, zhuyifei1999 commented on README.md
> +**Media Dubiety** is an IRC bot in channels defined in `~tools.media-dubiety/channels.json`. It sends messages such as:
`~tools.media-dubiety/channels.json` applies for this instance of the running bot.

2020-03-10 07:13 UTC, zhuyifei1999 commented on README.md
> +## T129845
No need to advertise it.

2020-03-10 07:13 UTC, zhuyifei1999 commented on README.md
> +The purpose of this project used to be **T129845**, but right now it's more like "*if abuse happens again we would know*".
No need to advertise it.

2020-03-10 07:19 UTC, Rohan-cod commented
> Look, I really don't think it's a good idea to advertise anti-abuse mechanisms on the "front page".
> 
> Example messages? Sure. People knows what this does.
> 
> Anything about T129845? No thanks. That was for your information only.

Done.

2020-03-10 08:30 UTC, zhuyifei1999 commented
Gonna add this additional patch and squash the commits:

```
From 8355833be40b40ba96b3a9f417b2648999662f71 Mon Sep 17 00:00:00 2001
From: YiFei Zhu <zhuyifei1999@gmail.com>
Date: Tue, 10 Mar 2020 03:23:25 -0500
Subject: [PATCH] README.md: Clarify channels def & use foobar for less
 obnoxious redaction

---
 README.md | 7 ++++---
 1 file changed, 4 insertions(+), 3 deletions(-)

diff --git a/README.md b/README.md
index 1a75d6c..eaf65ad 100644
--- a/README.md
+++ b/README.md
@@ -1,4 +1,5 @@
 # Media Dubiety
-**Media Dubiety** is an IRC bot in channels defined in `~tools.media-dubiety/channels.json`(When the bot is running). It sends messages such as:
-* `<media-dubiety> https://tinyurl.com/CentralAuth/REDACTED (3 edits) uploaded https://commons.wikimedia.org/wiki/File:REDACTED (56.7MiB, 5 min)`
-* `<media-dubiety> REDACTED blocks User:REDACTED on simplewiki for: Reciprocal block: Violating the "one-strike" rule`
+**Media Dubiety** is an IRC bot in channels defined in `~/channels.json`. It sends messages such as:
+
+* `<media-dubiety> https://tinyurl.com/CentralAuth/Foo (3 edits) uploaded https://commons.wikimedia.org/wiki/File:Bar.webm (56.7MiB, 5 min)`
+* `<media-dubiety> Baz blocks User:Foo on commonswiki for: Disposable account for uploading copyrighted content`
-- 
2.25.1
```

2020-03-10 08:32 UTC, closed without merging

2020-03-10 08:35 UTC, Rohan-cod commented
Do I have to send a new pr now?

2020-03-10 09:07 UTC, zhuyifei1999 commented
No, it has been "squash" merged.

2020-03-10 09:22 UTC, Rohan-cod commented
Okay 😀.